# Generated by Django 2.2.18 on 2022-03-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotmusic',
            old_name='artist',
            new_name='user',
        ),
        migrations.AddField(
            model_name='spotmusic',
            name='song_author',
            field=models.CharField(default='user1', max_length=50),
        ),
    ]
