# Generated by Django 2.2.18 on 2022-03-16 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_auto_20220316_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotmusic',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
