# Generated by Django 2.2.18 on 2022-03-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_auto_20220316_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotmusic',
            name='song_image',
            field=models.FileField(upload_to='song_image'),
        ),
    ]
