# Generated by Django 2.2.18 on 2022-03-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_auto_20220316_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotmusic',
            name='audio',
            field=models.FileField(upload_to='spotify/audio'),
        ),
        migrations.AlterField(
            model_name='spotmusic',
            name='song_image',
            field=models.FileField(upload_to='spotify/images'),
        ),
    ]
